### ISSUE TITLE
Add support Petkit Eversweet 5 Mini

### ISSUE THREAD

**Issue by OXOTH1K** [RobertD502/home-assistant-petkit#12]
Hi! Can you add support for this Fountaint. By default it adds with this elements:
![image](https://github.com/RobertD502/home-assistant-petkit/assets/19778219/5c5dc0ef-fc71-4e02-adac-8eee9b089a1d)

**Comment by RobertD502** [comment]
If it was added as a Eversweet 3 pro, then that means that the mini 5 is returning the same model number (W5) in the PETKIT api as the Eversweet 3 pro. What exactly are you missing? There are specific entities that are only created if you have a valid BLE relay (the BLE relay has to be setup inside of the PETKIT app prior to using this integration)

**Comment by OXOTH1K** [comment]
BLE Relay is Petkit Feeder? I haven't it. Data will be updated when I was connect to Fountain with phone app, and then connect with HA?

**Comment by RobertD502** [comment]
There are several PETKIT devices that can act as a relay (some feeders yes others no).

The only way to have access to a water fountain is via the main PETKIT account. Sharing water fountains to another user isn't possible.

The reason I am saying this is because, in order to pull the water fountain into Home Assistant, you have to use your main PETKIT account. However, when you do that, you will be signed out of your account on the mobile app. This is because of how PETKIT handles authentication - you can't be signed into more than one device at a time. So, you can't use this integration and then use the PETKIT app on your phone to update the data for the water fountain.

Realistically, pulling water fountains into Home Assistant will only be worthwhile if you have another PETKIT device that acts as a BLE relay. Otherwise, there is no way of getting updated data from the water fountain. This is solely because of how PETKIT handles accounts.

Since you only have a water fountain, your cheapest solution is to continue using the app instead of the integration. Otherwise, if you want data to be updated in Home Assistant for the water fountain, you'll need to get a PETKIT device that is capable of being set up as a BLE relay inside of the PETKIT app prior to using this integration.

**Comment by OXOTH1K** [comment]
Thanks a lot! I'll go to aliexpress)

**Comment by RobertD502** [comment]
Make sure that the device can be a relay. For example, the mini feeder pro can't but the infinity feeder and solo 3 feeder can.

**Comment by OXOTH1K** [comment]
Yes, I was already seen in app.

**Comment by RobertD502** [comment]
If you can, shoot me a message on discord. I'm interested in knowing what exactly the api is returning for your water fountain because it is weird that they would give the same model number for the Eversweet 3 pro and your water fountain.

**Comment by OXOTH1K** [comment]
Okay! How can I find you?

**Comment by RobertD502** [comment]
Link to the channel can be found at the beginning of the documentation.

**Comment by RobertD502** [comment]
Should correctly be identified now in [version 0.1.2](https://github.com/RobertD502/home-assistant-petkit/releases/tag/0.1.2)
