### ISSUE TITLE
Automated cleaning state shows up as unknown - Pura Max

### ISSUE THREAD

**Issue by hugocowan** [RobertD502/home-assistant-petkit#31]
![image](https://github.com/RobertD502/home-assistant-petkit/assets/10326958/4b52099b-af7b-4ba7-a029-b4fcfe1e6eac)

Hi there,

I noticed that the event that triggers when automated cleaning starts shows up as unknown in the log - see screenshot above. Would be great if it showed the event correctly.

**Comment by RobertD502** [comment]
Are you saying that this occurs when there is a scheduled cleaning? In order to figure out what code the litter box is returning while the automated cleaning is occurring, you'll need to have debug logging turned on for the integration. In addition, the logging will have to catch the exact moment when the litter box is returning the `workState` key. The best way to ensure this happens is:

If you know when the litter box is going to perform a scheduled cleaning, a few minutes prior to that:

1) Turn on debugging for the integration (via the integrations page)
2) Set the polling interval to 10 seconds
3) Once those two things are done, restart Home Assistant so the debugging setting goes into effect.

At that point you'll just wait for the litter box to finish the cleaning. When it has done so, turn off debugging for the integration (via the UI) which should result in a log file downloaded to your computer. Share this file with me through discord via a personal message - PetKit may return some user info within the data so it is better to share it with me directly than here publicly on github.

Also, be sure to change your polling interval back to what you had it before - PetKit may not be happy if your account is polling their servers every 10 seconds for hours and hours.
