### ISSUE TITLE
Integration not supported in UI?

### ISSUE THREAD

**Issue by tstill88** [RobertD502/home-assistant-petkit#48]
Im just following after the first step to go to the integrations page, click the plus and select Petkit. When i do i get a pop-up "This device cannot be added from the UI - You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information."

Not sure how to proceed as the setup for yaml config wasnt provided.

**Comment by RobertD502** [comment]
> Im just following after the first step to go to the integrations page, click the plus and select Petkit. When i do i get a pop-up "This device cannot be added from the UI - You can add this device by adding it to your 'configuration.yaml'. See the documentation for more information."
> 
> 
> 
> Not sure how to proceed as the setup for yaml config wasnt provided.

Please ensure you have downloaded/installed the correct integration - the other PETKIT integration doesn't use the UI for setup. If you previously used another PETKIT integration or installed it by mistake instead of the integration from my repo, you will need to delete the other integration prior to installing this one.
