### ISSUE TITLE
Battery state and status - Infinity Feeder

### ISSUE THREAD

**Issue by HiTechTLS** [RobertD502/home-assistant-petkit#54]
Hello!

First want to say this integration is awesome, and is what drove me to purchase this product, to replace an older Petwant smart feeder with no external connectivity, as well as a terrible app.

I noticed the battery state it not filling in HA, although the unit it-self mentions having an internal battery, and the users guide shows that the LEDs are indicating it working properly. 

Is this a limitation for this product specifically (that other models may not have issues with), or has something happened in updates that caused the battery status to no longer sync properly?

Thanks!

![image](https://github.com/RobertD502/home-assistant-petkit/assets/99000979/7804634e-5ab3-418e-b4f1-1a4a2969be7f)

**Comment by RobertD502** [comment]
This is covered in the documentation:

![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/c7e02af4-7934-4177-bc80-a31d6fe5f4fe)

If you were to unplug your feeder and have it run on batteries, you should eventually see the Battery status entity become available. In addition, the battery entity is more than likely showing a state of `not charging` because the battery is fully charged (your feeder is being supplied power and has fully charged its battery) - If you were to leave your feeder unplugged for a while to drain the battery some, it should show charging after getting plugged in.

**Comment by HiTechTLS** [comment]
Yes, see that now, sorry. Tested to see the Battery Status & Status both change with the power unplugging for longer than the update rate. Thanks!

**Comment by RobertD502** [comment]
All good!
