### ISSUE TITLE
Would it be possible to support trackers via API pooling?

### ISSUE THREAD

**Issue by igorsantos07** [RobertD502/home-assistant-petkit#57]
I used to run https://github.com/hasscc/petkit, but the stats support was very poor and today I realized the project got completely abandoned.

I was wondering if it would be possible to integrate collar tracker support to this project, using API pooling as that other project did - but of course, with the entries being proper statistical entities haha

Cheers!

**Comment by RobertD502** [comment]
I'm assuming you're referring to the PetKit Fit collar? I don't have any plans to support it in the near future as I haven't had much time lately and need to get the new YumShare feeders integrated first.

Out of curiosity...are you able to use the family share feature to share the collar with a second account? This is important since the primary account will need to be used with the integration - if you can't use the secondary account to connect to the collar via bluetooth (using the PetKit app), then the info pulled by the API will never be updated.

**Comment by igorsantos07** [comment]
Yep, correct, the collars!

Given the other integration was mostly useless, there's some time I don't use the collars again, but I can take them out of the wardrobe and put them to use, if you want a tester.

IIRC it was a frequently requested feature in the Petkit forums - no, [there was no way to share the collars](https://support.petkit.com/support/discussions/topics/51000414979), and I doubt it changed in the last 12 months.
That said, as I mentioned earlier, the other integration _was_ able to bring information onto HA without any extra configuration in regards to secondary accounts and all. The problems were:
- it didn't create devices, only spreaded out some entities - so it was complex to edit them all
- the update frequency was abismal and I'm not sure what triggered it. [At some point I got to the API directly](https://support.petkit.com/support/discussions/topics/51000483362) and noticed some info was missing, and the rest that's available is instant information, meaning it would need to pull from the API frequently to get accurate historical information.
- it didn't create stat entries, so even when data was pulled, it was mostly useless

You can see [in the aptly numbered issue 42](https://github.com/hasscc/petkit/issues/42) more details about missing features and a screenshot of actual data - I couldn't find a correlation between updated values and times/reasons for update.

**Comment by RobertD502** [comment]
The old integration was able to do what it did because it used the old API - PETKIT has changed their system and that is why users of newer devices such as water fountains weren't able to get any info from the old integration since that API didn't support newer devices. The new API doesn't allow one account to be used on multiple devices (i.e., you can't use the same account with this integration and the PETKIT app).

If you were to use this integration, you will HAVE to use the primary account with the integration. This means that you will not be able to use the PETKIT app at the same time with the same account. As a result, once you use the account connected to the collar with this integration, the data from the API will reflect the data that was available the last time the account was used with their app and connected to the collar via Bluetooth. You will not be able to get updated data from the collar since it requires using their app to initiate a Bluetooth connection to the collar to then send updated info to their servers.

PETKIT has made some changes to their family share feature (devices that you previously couldn't share, such as water fountains, can now be shared). I'd download the app, create a secondary account, sign in with your primary account, and see if sharing the collar to the secondary account is now an option. If it isn't, then adding support for the collar doesn't make much sense on account the data being stale and never being updated once you start using the account with this integration.
