### ISSUE TITLE
Feeding schedule

### ISSUE THREAD

**Issue by adam-kulagowski** [RobertD502/home-assistant-petkit#62]
Hi,

Is feeding plan/schedule (that will be programmed onto device) on the roadmap? I know that can use HA automation to achieve similar results but such scenario creates IMO to many parts that can fail.

If this matters I'm using Fresh Element Solo

Regards,
Adam

**Comment by RobertD502** [comment]
No plans to add feeding schedule manipulation - since feeding schedules are more of a set once/don't get changed often thing, I'd recommend creating a secondary PetKit account (to which the feeders have been shared to from the primary account) and making changes to the feeding schedule using the PetKit app.

**Comment by adam-kulagowski** [comment]
I was hoping to have everything in one place (even the onetime jobs 😉)

Thanks for the prompt response.

**Comment by forresthopkinsa** [comment]
FWIW, my main reason for looking for Petkit integrations in the first place was to periodically sync my feeder schedule with sunrise/sunset (my cat's circadian rhythm is unshakable)
