### ISSUE TITLE
Issues on pura max

### ISSUE THREAD

**Issue by override80** [RobertD502/home-assistant-petkit#68]
Hi @RobertD502 , since I added a Eversweet 3 fountain i'm experiencing issues with my pura max. Sometimes the cat litter just hangs, sometimes it restarts in the middle of a reset, sometimes it does not do the automatic cleaning. Sometimes it just shuts down and I have to unplug and plug it back to make it work. I honestly doubt that it's related to this integration, it seems more like a firmware issue or hardware problem.

Are you aware of any possible issue connected to BLE Relay and/or Pura Max like this ones?

**Comment by RobertD502** [comment]
Yes, this has been brought up in discord where we have narrowed it down to the BLE relay - the current default polling interval (2 minutes) causes the Pura Max to lock up. This issue is caused by the firmware in the Pura Max and it not being able to handle initiating the BLE relay every 2 minutes.

To get around this, change the polling interval to 7 minutes. I've already completed the fix for this issue and it will be in the next release - in the next release, you can change the polling interval back to 2 minutes since the library will have a separate time check that will only initiate the BLE relay if it has been 7 minutes since the last time the BLE relay has been initiated (this way you can still get new data from your devices every 2 minutes and only check for new water fountain data every 7 minutes).

**Comment by override80** [comment]
Thank you for the feedback! I raised the polling interval to 420s and wait for the next release.

**Comment by override80** [comment]
Hi @RobertD502 , i had to set it to 450s.

Sometimes I still have issues btw, automatic cleaning getting canceled, litter not cleaning... It seems that it's happening when getting data during cleaning.

**Comment by override80** [comment]
Ouch! No i didn't! Let me try to disconnect and reconnect! Thanks

**Comment by override80** [comment]
Hi @RobertD502 , it's still sporadically happening to me, even after setting the 450s timeout. I disabled the intergration for a week, today i enabled it again and the litter got stuck halfway up. Display off, no way to get it working except unplugging and replugging.
Do you think there is something else i can try?

**Comment by RobertD502** [comment]
Only thing you can do is keep bumping the time higher and higher until you find a sweet spot.

**Comment by override80** [comment]
Yeah it was set up to 600 today and still happened - i should fine a safe value. Is the fix already available on main or should i wait for the release?

**Comment by RobertD502** [comment]
Not available on the main repo. However, the next release will have a set time of 420 with an option to manually set it to a higher value. This way you will be able to set the BLE relay time to a higher value that is separate from the rest of the polling process.

Increasing the time is the only potential fix since the culprit is something within the Max firmware. Have you checked to see, using the app, if there is a firmware update?

**Comment by override80** [comment]
Yes I did, unfortunately I'm on latest and still having the issue sometimes. Do you think that polling during cat litter operations could be the issue? For example, if I don't poll while cleaning, there will be no issues?

**Comment by override80** [comment]
I'll give this manifest.json a try and see if it gets better! :crossed_fingers: Thanks!

**Comment by RobertD502** [comment]
> Yes I did, unfortunately I'm on latest and still having the issue sometimes. Do you think that polling during cat litter operations could be the issue? For example, if I don't poll while cleaning, there will be no issues?

Potentially, but since the data is obtained via polling (since PETKIT doesn't use push), you wouldn't know that the litter box is cleaning until you do a poll exactly at the time it is happening.

You could test to see if the BLE relay is causing the issue while the litter box is cleaning by performing manual tests - when the litter box is cleaning use the PETKIT app (with your phone's Bluetooth off to force it to use the remote relay for a water fountain) to initiate the BLE relay by clicking on the water fountain and noting the blue cloud icon.

**Comment by RobertD502** [comment]
> Hi @RobertD502 , it seems that freezing the app on android prevents the issue from happening... even if the Petkit app i'm using on android is configured with a secondary account, could there be any connection?

Possibly. By freezing do you mean you force quit and kept the app (which uses your secondary account) closed / didn't use it?

**Comment by Rumlik** [comment]
Hi,
I just want to you know, I have similar problem like you @override80 . Same scenario at home with Pura Max and Eversweet 3. You are not alone :)

**Comment by override80** [comment]
> Hi,
> I just want to you know, I have similar problem like you @override80 . Same scenario at home with Pura Max and Eversweet 3. You are not alone :)

I see some improvements if i disable the Petkit app on the phone, even if its using a different account

**Comment by Rumlik** [comment]
> > Hi,
> > I just want to you know, I have similar problem like you @override80 . Same scenario at home with Pura Max and Eversweet 3. You are not alone :)
> 
> I see some improvements if i disable the Petkit app on the phone, even if its using a different account

But I usualy using the petkit app on my phone, instead HA :(

**Comment by override80** [comment]
Hi @RobertD502 , is there any other way se can contribute?

At this point I guess the petkit app has a role - I have no more issues after disabling it.

**Comment by RobertD502** [comment]
> Hi @RobertD502 , is there any other way we can contribute?
> 
> 
> 
> At this point I guess the petkit app has a role - I have no more issues after disabling it.

If it is the app and integration both initiating the relay that is causing the issue, there isn't anything from the integration side that can be done - this is a bug in the litter box firmware (such issues aren't present on feeders if the relay is initiated through them through the app and integration).

I'll likely add an option for users to be able to disable using the BLE relay through the integration if they want to instead stick to using the PetKit app.
