### ISSUE TITLE
PETKIT Pura Air - Bluetooth Support

### ISSUE THREAD

**Issue by pedromrg** [RobertD502/home-assistant-petkit#75]
Hi there,

Any plans do integrate PETKIT Pura Air using Bluetooth Proxy? 

Thanks! 

Greate custom component!

**Comment by RobertD502** [comment]
Are you referring to this product?

![image](https://github.com/RobertD502/home-assistant-petkit/assets/52541649/a987c51d-cedd-40a0-b946-481587742c1d)

If so, no because this is not a smart product (no control via Bluetooth or WiFi).

If you are referring to the K1 purifier that is used with litter boxes, support is already included in the integration if you have a litter box linked to the purifier. It is not supported as a standalone device. I am not aware of the K1 being able to be controlled via a proxy besides when it is associated with a PetKit litter box.
