### ISSUE TITLE
PetKit Air Magicube Smart Odor Eliminator

### ISSUE THREAD

**Issue by Traxeronus** [RobertD502/home-assistant-petkit#8]
Hi,
would you please implement PetKit Air Magicube Smart Odor Eliminator? Or do you plan it?

Thanks

**Comment by lelez84** [comment]
Hi Robert and thank you SO MUCH for your work. I managed to install, despite not knowing Ha, your integration. it accepts my credentials but I can't find anything in entity, only now I think I understand that this is due to the fact that I have a pure max. is it correct in your opinion? do you plan to release an update soon? is this why i can't find entities on Ha? thank you very much!!!

**Comment by lelez84** [comment]
> It would be possible. However, I am currently working on integrating the Pura Max, so, it wouldn't be until after that is done. In the meantime, you can join the discord server and send me a PM so I can keep you in the loop about availability.



> It would be possible. However, I am currently working on integrating the Pura Max, so, it wouldn't be until after that is done. In the meantime, you can join the discord server and send me a PM so I can keep you in the loop about availability.

Hi Robert and thank you SO MUCH for your work. I managed to install, despite not knowing Ha, your integration. it accepts my credentials but I can't find anything in entity, only now I think I understand that this is due to the fact that I have a pure max. is it correct in your opinion? do you plan to release an update soon? is this why i can't find entities on Ha? thank you very much!!!

**Comment by RobertD502** [comment]
I haven't received any contact since the first request so no plans were made to add it.

**Comment by RobertD502** [comment]
If you could please personally message me on the discord server that would work. Credentials sharing or any logging containing identifiable information would be visible to the public if shared here.
