### ISSUE TITLE
Pura MAX: Unknown pet

### ISSUE THREAD

**Issue by koichirose** [RobertD502/home-assistant-petkit#83]
My Pura MAX sometimes doesn't detect the pet by weight.
The official app can still show the last use duration and weight ("Pet just spent 1m39s in the litter box, weighing record 4.1kg"), is there a way to have this info with the home assistant integration as well?

**Comment by RobertD502** [comment]
It would require building out a separate "Unknown" pet device and parsing through daily logs to see if there were any unknown pet usages and weights associated with them. There is a cutoff when it comes to PetKit associating a measured weight with a pet (I'm not sure what that is since I don't own their litter boxes) - the easiest way to fix this is to look at the most recent weights (including Unknown measurement that are associated with the pet) of the pet in question and adjust the set pet weight so that the set weight falls in the range that the litter box tends to measure for said pet.

**Comment by koichirose** [comment]
I tried, but for some reason if a cat weighs 4.1kg, then 4.2kg is not recognized even if I manually adjust it over and over.
Also, sometimes the cat just leans on the box and it registers 3kg, so I'd lose that event (not a big issue). Thank you.
